### ISSUE TITLE
[TODO] Documentation for YAK itself

### ISSUE THREAD

**Issue by panagiks** [norisMIKE/yak#5]
Document:

- [ ] Approach and goals
- [ ] Command and options
- [ ] Expected behavior
- [ ] Scope, what is and isn't
